name: capstone_vocalavida
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Exo-Light.ttf
          weight: 300
  uses-material-design: true

